drivers: staging: ion: Fix merge conflict
../drivers/staging/android/ion/ion.c:550:27: error: static declaration of '__ion_alloc' follows non-static declaration
static struct ion_handle *__ion_alloc(
                          ^
./../include/linux/../../drivers/staging/android/ion/ion.h:132:20: note: previous declaration is here
struct ion_handle *__ion_alloc(struct ion_client *client, size_t len,